# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/srv/data/vmshare/kicksecure/git/sysmaint-panel/ui/ui_background.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BackgroundWindow(object):
    def setupUi(self, BackgroundWindow):
        BackgroundWindow.setObjectName("BackgroundWindow")
        BackgroundWindow.resize(400, 300)
        BackgroundWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #3b187b, stop:1 #a9def2);")

        self.retranslateUi(BackgroundWindow)
        QtCore.QMetaObject.connectSlotsByName(BackgroundWindow)

    def retranslateUi(self, BackgroundWindow):
        _translate = QtCore.QCoreApplication.translate
        BackgroundWindow.setWindowTitle(_translate("BackgroundWindow", "Background Window"))
