# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/srv/data/vmshare/kicksecure/git/sysmaint-panel/ui/ui_installsoftware.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InstallSoftwareWindow(object):
    def setupUi(self, InstallSoftwareWindow):
        InstallSoftwareWindow.setObjectName("InstallSoftwareWindow")
        InstallSoftwareWindow.resize(331, 128)
        self.verticalLayout = QtWidgets.QVBoxLayout(InstallSoftwareWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(InstallSoftwareWindow)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.packageLineEdit = QtWidgets.QLineEdit(InstallSoftwareWindow)
        self.packageLineEdit.setObjectName("packageLineEdit")
        self.verticalLayout.addWidget(self.packageLineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.searchButton = QtWidgets.QPushButton(InstallSoftwareWindow)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.installButton = QtWidgets.QPushButton(InstallSoftwareWindow)
        self.installButton.setObjectName("installButton")
        self.horizontalLayout.addWidget(self.installButton)
        self.cancelButton = QtWidgets.QPushButton(InstallSoftwareWindow)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(InstallSoftwareWindow)
        QtCore.QMetaObject.connectSlotsByName(InstallSoftwareWindow)

    def retranslateUi(self, InstallSoftwareWindow):
        _translate = QtCore.QCoreApplication.translate
        InstallSoftwareWindow.setWindowTitle(_translate("InstallSoftwareWindow", "Install Software"))
        self.label.setText(_translate("InstallSoftwareWindow", "Enter a package name to install or search for:"))
        self.searchButton.setText(_translate("InstallSoftwareWindow", "Search"))
        self.installButton.setText(_translate("InstallSoftwareWindow", "Install"))
        self.cancelButton.setText(_translate("InstallSoftwareWindow", "Cancel"))
