#!/bin/bash

## Copyright (C) 2024 - 2024 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

xfwm4 &
# Needed to prevent window ordering problems
sleep 1;
sysmaint-panel
