#!/bin/bash

## Copyright (C) 2024 - 2024 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

echo "[Seat:*]
autologin-user=sysmaint
autologin-session=sysmaint-session" \
   | sponge -- '/etc/lightdm/lightdm.conf.d/99_sysmaint-boot.conf'

echo "[Desktop]
Session=sysmaint-session" \
   | sponge -- '/home/sysmaint/.dmrc'
